---
# tasks file for ansible-nginx-example
- name: Configure selinux to be permisive on RedHat
  include_tasks: common/setup-selinux.yaml
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install nginx package
  block: 
    - name: Installing package for Debian
      include_tasks: package/setup-debian.yaml
      when: ansible_facts['os_family'] == 'Debian'
    - name: Installing package for Centos
      include_tasks: package/setup-rhel.yaml
      when: ansible_facts['os_family'] == 'RedHat'

- name: Setup firewall for allow http(s)
  block: 
  - name: Setup firewall for Ubuntu
    include_tasks: common/setup-ufw.yaml
    when: ansible_facts['os_family'] == 'Debian'
  - name: Setup firewall for Centos
    include_tasks: common/setup-firewall-cmd.yaml
    when: ansible_facts['os_family'] == 'RedHat'

- name: Start service nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started